openapi: 3.0.1
info:
  title: Staff
  version: 0.1.0
servers:
- url: "{server}:{port}/Staff"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /GetStaffByStaffNo:
    get:
      operationId: getGetstaffbystaffno
      parameters:
      - name: Staff_No
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
            text/plain:
              schema:
                type: string
  /GetByCourseName:
    get:
      operationId: getGetbycoursename
      parameters:
      - name: Course_Name
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
            text/plain:
              schema:
                type: string
  /GetByOfficeNo:
    get:
      operationId: getGetbyofficeno
      parameters:
      - name: Office_Num
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
            text/plain:
              schema:
                type: string
  /addstaffRecord:
    post:
      operationId: postAddstaffrecord
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
  /DeleteStaff/{staff_num}:
    delete:
      operationId: deleteDeletestaffStaffNum
      parameters:
      - name: staff_num
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /updateStaffMembers:
    put:
      operationId: putUpdatestaffmembers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Lecturer:
      required:
      - CoursesName
      - Office_No
      - Staff_Name
      - Staff_No
      type: object
      properties:
        Staff_No:
          type: string
        Staff_Name:
          type: string
        Office_No:
          type: string
        CoursesName:
          type: string
