// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type Lecturer record {
    string Staff_No;
    string Staff_Name;
    string Office_No;
    string CoursesName;
};
